### ISSUE TITLE
bug 1.14.2 paper

### ISSUE THREAD

**Issue by slvlr** [sainttx/Holograms#47] opened 2019-06-04 00:39 UTC
https://pastebin.com/nC8ZJvPs

**Comment by slvlr** [comment] 2019-06-04 00:40
and this  is this an issue with crates or holograms? https://pastebin.com/VsmTkbr6

**Comment by MamiyaOtaru** [comment] 2019-06-04 21:46
bukkitEntity is private now.  https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/fa71719350d15fd5d5091c4fe45ff2e86a95371c

**Comment by sainttx** [comment] 2019-06-07 03:50
Duplicate of #45

**Closed by sainttx** 2019-06-07 03:50 UTC
