### ISSUE TITLE
Internal Error has Occurred

### ISSUE THREAD

**Issue by QuazArxx** [sainttx/Holograms#48] opened 2019-06-05 15:23 UTC
https://pastebin.com/Sas4akeh

Running Spigot 1.14.2

**Comment by MamiyaOtaru** [comment] 2019-06-06 01:58
this is a duplicate of https://github.com/sainttx/Holograms/issues/47 and https://github.com/sainttx/Holograms/issues/45

**Comment by QuazArxx** [comment] 2019-06-06 04:17
You say this but I don't understand either post because it didn't have what
I was looking for and your response to them is too technical. Please
explain why this is not working and what I can do to fix it.

**Comment by sainttx** [comment] 2019-06-07 03:50
Duplicate of #45

**Closed by sainttx** 2019-06-07 03:50 UTC

**Comment by QuazArxx** [comment] 2019-06-07 09:17
You close it but still have not answered my question. Duplicate or not the answer is not understood and my problem is not resolved. If this is how you treat people then I won’t bother using your broken sham of a plugin
