### ISSUE TITLE
Holographic display expanding past the last character when using special characters. 

### ISSUE THREAD

**Issue by rubota** [sainttx/Holograms#18] opened 2016-07-23 00:17 UTC
For some reason, whenever I use a utf-8 character, the transparent part of the display extends past the last character and makes the entire display off center. The more special characters I use, the worse it becomes. Even using 3 social characters, the entire display is off centered by 1/3. How do I fix this?

I'm using the latest update 1.10, and using spigot 1.10.  I've tried different versions and they all do the exact same thing. I've seen many servers use special characters and this problem does not persist on theirs.

**Comment by rubota** [comment] 2016-07-23 00:18
![2016-07-22_19 17 52](https://cloud.githubusercontent.com/assets/12865829/17074463/1276ecf2-5041-11e6-82e0-1ae01ad4bb4e.png)

**Comment by rubota** [comment] 2016-07-23 00:22
Notice this one does NOT go last the final character

![2016-07-22_19 21 17](https://cloud.githubusercontent.com/assets/12865829/17074507/901a9848-5041-11e6-83ad-3ad4a7693cf0.png)

**Comment by rubota** [comment] 2016-07-23 00:24
Simple example of the special character causing the transparent end to extend far past the final character. 

![2016-07-22_19 23 16](https://cloud.githubusercontent.com/assets/12865829/17074542/f1cb4fec-5041-11e6-8ede-bf12bae9af65.png)

**Comment by rubota** [comment] 2016-07-23 01:12
&e&m&l---&6&m-&6}>&6[1]&e[<]&6[1]<{&m&l-&e&m&l---

**Comment by sainttx** [comment] 2016-07-23 04:01
I believe this is a minecraft bug caused by the way special characters are rendered. It seems as though when the Minecraft client doesn't know the character it may be defaulting to a specific width which is wider than the character. I've ran into this issue even using special characters in the chat box where the width was off centre. I don't think there is a fix for this, you might want to consider reporting it on the Mojang bug tracker.

**Comment by rubota** [comment] 2016-07-23 04:04
ok, thank you for replying. I’ll send a ticket in

**Closed** 2016-08-30 03:13 UTC
