### ISSUE TITLE
Holograms disappear after restart the server

### ISSUE THREAD

**Issue by Hu5ker** [sainttx/Holograms#26] opened 2017-01-04 21:26 UTC
So, I configure my holograms successfully via commands, then I restart the server for X reason and the next error appears on console. And the holograms are not showing after the restart:

`[Server] WARN [Holograms] Task #26 for Holograms v2.4.0-SNAPSHOT generated an exception
 [Server] INFO java.lang.NullPointerException
 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftChunk.getHandle(CraftChunk.java:44) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftChunk.<init>(CraftChunk.java:30) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
 [Server] INFO at com.sainttx.holograms.nms.v1_8_R3.HologramEntityControllerImpl.addEntityToWorld(HologramEntityControllerImpl.java:70) ~[?:?]
 [Server] INFO at com.sainttx.holograms.nms.v1_8_R3.HologramEntityControllerImpl.spawnNameable(HologramEntityControllerImpl.java:39) ~[?:?]
 [Server] INFO at com.sainttx.holograms.api.line.TextLine.show(TextLine.java:47) ~[?:?]
 [Server] INFO at com.sainttx.holograms.api.Hologram.addLine(Hologram.java:130) ~[?:?]
 [Server] INFO at com.sainttx.holograms.api.Hologram.addLine(Hologram.java:119) ~[?:?]
 [Server] INFO at com.sainttx.holograms.ManagerImpl.load(ManagerImpl.java:54) ~[?:?]
 [Server] INFO at com.sainttx.holograms.HologramPlugin.lambda$onEnable$0(HologramPlugin.java:49) ~[?:?]
 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]`

This is the content at holograms.yml:

`holograms:
  entradanortesrv:
    location: survival;-44.318526399258914;67.0;898.3483877581078;4.800071;176.93701
    lines:
    - §d§k!!!!§a Entrada Norte §d§k!!!!
  entradaoestesrv:
    location: survival;-72.3353389003716;67.0;926.2834818315296;4.0500574;89.48718
    lines:
    - §d§k!!!!§a Entrada Oeste §d§k!!!!
  entradasursrv:
    location: survival;-44.63281621703896;67.0;954.237236262998;7.3500566;356.78748
    lines:
    - §d§k!!!!§a Entrada Este §d§k!!!!
  entradaestesrv:
    location: survival;-16.321892611608572;67.0;926.3811150634901;-0.5999343;268.43707
    lines:
    - §d§k!!!!§a Entrada Este §d§k!!!!
  entrada1:
    location: survival;-44.478320864490314;67.0;798.6201094301554;4.5281334;183.02478
    lines:
    - §aDespues de la linea §9azul
    - §apuedes construir
  entrada2:
    location: survival;-44.5032091377419;67.0;1054.8651818332705;4.978144;0.47607422
    lines:
    - §aDespues de la linea §9azul
    - §apuedes construir
  entrada3:
    location: survival;83.12938878529258;67.0;926.5948707571132;8.876807;268.07324
    lines:
    - §aDespues de la linea §9azul
    - §apuedes construir
  entrada4:
    location: survival;-172.64972876972945;67.0;926.6343757187501;3.0268717;93.77283
    lines:
    - §aDespues de la linea §9azul
    - §apuedes construir
`

I would thank any help, :smiley:

**Comment by Hu5ker** [comment] 2017-01-05 06:19
Nevermind, I found a better plugin. Thanks anyways.

**Comment by MTM123** [comment] 2017-01-06 11:39
Have the same problem. From what I can tell it arises when config contains hologram location in chuck that is either not generated or/and outside the world border if it is set.

**Comment by sainttx** [comment] 2017-01-08 16:17
I'll get a bandaid fix going where the Hologram will just fail to load when the chunk cannot be created, should at least let all other valid Holograms load

**Comment by udozockt** [comment] 2017-03-13 21:56
+1

**Comment by sainttx** [comment] 2017-03-14 04:48
Fixed in 4e001c5

**Comment by udozockt** [comment] 2017-03-24 20:12
Same bug, now with another exception.

**Comment by udozockt** [comment] 2017-03-25 01:46
It works, if I create a new hologram and reload the server. If I do a restart, all holograms are gone and I get many console errors.

**Comment by sainttx** [comment] 2017-03-25 02:04
Please post the error log

**Comment by udozockt** [comment] 2017-03-25 02:29
`[02:43:25] [Server thread/WARN]: [HologramSystem] Failed to spawn Hologram "UDO_zockt"
com.sainttx.holograms.api.exceptions.HologramEntitySpawnException: Attempted to spawn hologram entity in invalid chunk
        at com.sainttx.holograms.nms.v1_8_R3.HologramEntityControllerImpl.addEntityToWorld(HologramEntityControllerImpl.java:70) ~[?:?]
        at com.sainttx.holograms.nms.v1_8_R3.HologramEntityControllerImpl.spawnNameable(HologramEntityControllerImpl.java:41) ~[?:?]
        at com.sainttx.holograms.api.line.TextLine.show(TextLine.java:45) ~[?:?]
        at com.sainttx.holograms.api.Hologram.addLine(Hologram.java:80) ~[?:?]
        at com.sainttx.holograms.api.Hologram.addLine(Hologram.java:75) ~[?:?]
        at com.sainttx.holograms.ManagerImpl.load(ManagerImpl.java:50) ~[?:?]
        at com.sainttx.holograms.HologramPlugin.lambda$onEnable$0(HologramPlugin.java:43) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [Spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_8_R3.CraftChunk.getHandle(CraftChunk.java:44) ~[Spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftChunk.<init>(CraftChunk.java:30) ~[Spigot.jar:git-Spigot-db6de12-18fbb24]
        at com.sainttx.holograms.nms.v1_8_R3.HologramEntityControllerImpl.addEntityToWorld(HologramEntityControllerImpl.java:68) ~[?:?]
        ... 13 more`

**Comment by udozockt** [comment] 2017-03-25 04:02
nmsChunk is for some reason empty. Do you have an idea?

**Closed** 2019-06-07 03:59 UTC
